# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='url',
        ),
        migrations.DeleteModel(
            name='PIN',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
